---
stages:
  - lint
  - test
  - autorel
  - build
  - release

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

conform:
  stage: lint
  image: cr.agilicus.com/corp-tools/build-containers/conform
  script: |
    [ -n "$CI_MERGE_REQUEST_ID" ] && /usr/local/bin/conform enforce || true

lint:
  stage: lint
  image: node:12
  script: |
    env CYPRESS_INSTALL_BINARY=0 npm i
    ./node_modules/.bin/ng lint

audit:
  stage: test
  image: node:12
  cache:
    policy: pull
  script: |
    env CYPRESS_INSTALL_BINARY=0 npm install --unsafe-perm
    ./node_modules/.bin/ng lint
    npm audit

# unitTest:
#   stage: test
#   image: cr.agilicus.com/corp-tools/angular-build
#   cache:
#     policy: pull
#   script: |
#     #set +e
#     #Xvfb &
#     #xpid=$!
#     #DISPLAY=:0
#     #export DISPLAY
#     npm i
#     chown -R node:node .
#     su node -c "npm run test"
#     #res=$?
#     #kill $xpid
#     #exit $res

#
# Run `conventional-changelog -p angular -i CHANGELOG.md -s -r 0`
# the first time to generate the initial CHANGELOG.md from empty
#
# (only on the master branch) created a 'standard release'
# [see](https://github.com/conventional-changelog/standard-version)
# - update CHANGELOG.md
# - create a tag vM.m.b
# - push tag to repo
# - push CHANGELOG.md to repo
# The use of 'conventional-commit' messages is required (fix/feat)
# see [conventional-commits](https://www.conventionalcommits.org/)
#
autorel:
  stage: autorel
  cache: {}
  image: cr.agilicus.com/corp-tools/build-containers/release
  script: |
    set -x
    if [ -n "$CI_COMMIT_TAG" ]
    then
      echo "Skip autorel, CI_COMMIT_TAG=$CI_COMMIT_TAG is present"
    else
      node-release
    fi
  only:
    - master
  except:
    refs:
      - tags
    variables:
      - $CI_COMMIT_MESSAGE =~ /^chore\(release\)/

# This is run both in the 'autorel' case and when not
# In the 'autorel' case CI_COMMIT_TAG is set, and we should
# keep the release somewhere
build:
  stage: build
  cache: {}
  image: cr.agilicus.com/corp-tools/docker-compose
  services:
    - name: docker:dind
  script: |
    std-build-tag-push

#
# If a tag is present, this could mean that the 'autorel' has
# fired, and that a build of that is now present, we might
# choose to push to external repo etc.
#
release:
  stage: release
  cache: {}
  image: python:3
  script: |
    echo "A new release, tag is $CI_COMMIT_TAG"
    # nothing to do here
  except:
    - branches
  only:
    - tags
