---
stages:
  - lint
  - test
  - autorel
  - build
  - release
  - smoke


conform:
  stage: lint
  image: cr.agilicus.com/corp-tools/build-containers/conform
  script: |
    [ -n "$CI_MERGE_REQUEST_ID" ] && /usr/local/bin/conform enforce || true

lint:
  stage: lint
  image: node:12
  script: |
    env CYPRESS_INSTALL_BINARY=0 npm i
    ./node_modules/.bin/ng lint
    npm audit

#
# Run `conventional-changelog -p angular -i CHANGELOG.md -s -r 0`
# the first time to generate the initial CHANGELOG.md from empty
#
# (only on the master branch) created a 'standard release'
# [see](https://github.com/conventional-changelog/standard-version)
# - update CHANGELOG.md
# - create a tag vM.m.b
# - push tag to repo
# - push CHANGELOG.md to repo
# The use of 'conventional-commit' messages is required (fix/feat)
# see [conventional-commits](https://www.conventionalcommits.org/)
#
autorel:
  stage: autorel
  image: cr.agilicus.com/corp-tools/build-containers/release
  script: |
    set -x
    if [ -n "$CI_COMMIT_TAG" ]
    then
      echo "Skip autorel, CI_COMMIT_TAG=$CI_COMMIT_TAG is present"
    else
      node-release
    fi
  only:
    - master
  except:
    refs:
      - tags
    variables:
      - $CI_COMMIT_MESSAGE =~ /^chore\(release\)/


# This is run both in the 'autorel' case and when not
# In the 'autorel' case CI_COMMIT_TAG is set, and we should
# keep the release somewhere
build:
  stage: build
  needs: []
  image: cr.agilicus.com/corp-tools/build-containers/img-build
  script: |
    std-build-tag-push

#
# If a tag is present, this could mean that the 'autorel' has
# fired, and that a build of that is now present, we might
# choose to push to external repo etc.
#
release:
  stage: release
  cache: {}
  image: python:3
  script: |
    echo "A new release, tag is $CI_COMMIT_TAG"
    # nothing to do here
  except:
    - branches
  only:
    - tags

# Very simple smoke test, check packages are running etc
smoke:
  stage: smoke
  image: ${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_COMMIT_REF_SLUG}
  needs: [build]
  cache: {}
  script: |
    /usr/local/openresty/bin/openresty -t -c /usr/local/openresty/nginx/conf/nginx.conf
    /usr/local/openresty/bin/openresty -g "daemon off;" > /tmp/log 2>&1 &
    nretry=0
    set +e
    until [ $nretry -eq 10 ] || curl -s http://localhost:5000 >/dev/null 2>&1
    do
        echo "Wait for local daemon to come up... $nretry"
        sleep 1
        nretry=$((nretry + 1))
    done
    echo "Took $nretry loops"
    [ $nretry -eq 10 ] && exit 1
    set -e
    set +x
    echo "Check for success"
    grep -q '"response_code": 200' /tmp/log
    curl -s localhost:5000/ | grep -q "<title>Sample Angular Authentication</title>"
    kill $(cat /tmp/pid)
    echo "Smoke test completed"
  except:
    refs:
      - tags
    variables:
      - $CI_COMMIT_MESSAGE =~ /^chore\(release\)/
